In [1]:
import pandas as pd
import glob

csv_files = glob.glob("*.csv")
df_list = [pd.read_csv(file) for file in csv_files]
df = pd.concat(df_list, ignore_index=True)

In [2]:
df

,model,test_acc,test_nll,test_ece,test_brier,test_auc,seed,dtype,device,backbone,...,prior_opt_iters,optimize_hyper_parameters,train_time_s,eval_time_s,batch_size,features,lr,laplace_iters,use_embedding,sqrt
0,Laplace,0.9437,0.203734,0.024071,0.088288,0.929494,1234,float32,cuda,resnet56,...,1000,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALaplace,0.9400,0.243292,0.027378,0.098130,0.898393,1234,float32,cuda,resnet44,...,1000,True,2595.57,11.05,5.0,100.0,0.00005,100000.0,False,False
2,ALaplace,0.9397,0.234151,0.016787,0.097914,0.873060,1234,float32,cuda,resnet44,...,1000,True,2510.80,11.62,5.0,200.0,0.00005,100000.0,False,False
3,ALaplace,0.9434,0.261581,0.055121,0.104352,0.906987,1234,float32,cuda,resnet56,...,1000,True,3069.49,12.53,5.0,300.0,0.00005,100000.0,False,False
4,Laplace,0.9400,0.230597,0.026338,0.096835,0.876217,1234,float32,cuda,resnet44,...,1000,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALaplace,0.9393,0.292622,0.076459,0.117055,0.820972,1234,float32,cuda,resnet44,...,1000,True,2466.44,10.90,5.0,500.0,0.00005,100000.0,False,False
6,ALaplace,0.9431,0.340771,0.125868,0.133081,0.892392,1234,float32,cuda,resnet56,...,1000,True,3054.99,12.62,5.0,500.0,0.00005,100000.0,False,False
7,ALaplace,0.9437,0.227405,0.023744,0.095007,0.914674,1234,float32,cuda,resnet56,...,1000,True,3099.27,12.81,5.0,200.0,0.00005,100000.0,False,False
8,ALaplace,0.9398,0.241812,0.022408,0.100881,0.842197,1234,float32,cuda,resnet44,...,1000,True,2471.93,11.36,5.0,300.0,0.00005,100000.0,False,False
9,ALaplace,0.9258,0.274175,0.035559,0.117510,0.895033,1234,float32,cuda,resnet20,...,1000,True,1456.20,7.91,5.0,100.0,0.00005,100000.0,False,False
10,ALaplace,0.9258,0.261697,0.029491,0.115537,0.888397,1234,float32,cuda,resnet20,...,1000,True,1438.60,8.87,5.0,300.0,0.00005,100000.0,False,False
11,ALaplace,0.9351,0.267116,0.033863,0.104528,0.934008,1234,float32,cuda,resnet32,...,1000,True,2043.82,9.99,5.0,100.0,0.00005,100000.0,False,False
12,ALaplace,0.9256,0.251531,0.022058,0.114025,0.885637,1234,float32,cuda,resnet20,...,1000,True,1459.51,8.06,5.0,500.0,0.00005,100000.0,False,False
13,ALaplace,0.9352,0.252609,0.026254,0.103256,0.924395,1234,float32,cuda,resnet32,...,1000,True,2043.48,9.90,5.0,200.0,0.00005,100000.0,False,False
14,ALaplace,0.9257,0.267225,0.032431,0.116414,0.894121,1234,float32,cuda,resnet20,...,1000,True,1447.22,7.47,5.0,200.0,0.00005,100000.0,False,False
15,Laplace,0.9355,0.251843,0.029178,0.102786,0.917649,1234,float32,cuda,resnet32,...,1000,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ALaplace,0.9437,0.218156,0.021387,0.090550,0.947338,1234,float32,cuda,resnet56,...,1000,True,3053.46,13.24,5.0,100.0,0.00005,100000.0,False,False
17,Laplace,0.9255,0.265901,0.023835,0.116038,0.884001,1234,float32,cuda,resnet20,...,1000,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,ALaplace,0.9350,0.244238,0.017446,0.102886,0.931788,1234,float32,cuda,resnet32,...,1000,True,2053.79,9.51,5.0,300.0,0.00005,100000.0,False,False
19,ALaplace,0.9344,0.250693,0.021553,0.106565,0.897543,1234,float32,cuda,resnet32,...,1000,True,2040.42,9.60,5.0,500.0,0.00005,100000.0,False,False

In [3]:
df = df.drop(columns=["dtype", "device", "optimize_hyper_parameters"], axis=1)

In [4]:

grouped = (
    df.groupby(
        ["model", "backbone", "features", "lr", "use_embedding", "sqrt", "batch_size"],
        dropna=False
    ).mean()
)

with pd.option_context(
    "display.max_rows", None,        # show every row
    "display.max_columns", None,     # show every column
    "display.width", None,           # don’t wrap long lines
):
    display(grouped)                 # or just `grouped` in a cell

                                                                   test_acc  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0           0.9258
                  200.0    0.00005 False         False 5.0           0.9257
                  300.0    0.00005 False         False 5.0           0.9258
                  500.0    0.00005 False         False 5.0           0.9256
         resnet32 100.0    0.00005 False         False 5.0           0.9351
                  200.0    0.00005 False         False 5.0           0.9352
                  300.0    0.00005 False         False 5.0           0.9350
                  500.0    0.00005 False         False 5.0           0.9344
         resnet44 100.0    0.00005 False         False 5.0           0.9400
                  200.0    0.00005 False         False 5.0           0.9397
                  300.0    0.00005 False         False 5.0           0.9398
                  500.0    0.00005 False         False 5.0           0.9393
         resnet56 100.0    0.00005 False         False 5.0           0.9437
                  200.0    0.00005 False         False 5.0           0.9437
                  300.0    0.00005 False         False 5.0           0.9434
                  500.0    0.00005 False         False 5.0           0.9431
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN           0.9255
         resnet32 NaN      NaN     NaN           NaN   NaN           0.9355
         resnet44 NaN      NaN     NaN           NaN   NaN           0.9400
         resnet56 NaN      NaN     NaN           NaN   NaN           0.9437

                                                                   test_nll  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0         0.274175
                  200.0    0.00005 False         False 5.0         0.267225
                  300.0    0.00005 False         False 5.0         0.261697
                  500.0    0.00005 False         False 5.0         0.251531
         resnet32 100.0    0.00005 False         False 5.0         0.267116
                  200.0    0.00005 False         False 5.0         0.252609
                  300.0    0.00005 False         False 5.0         0.244238
                  500.0    0.00005 False         False 5.0         0.250693
         resnet44 100.0    0.00005 False         False 5.0         0.243292
                  200.0    0.00005 False         False 5.0         0.234151
                  300.0    0.00005 False         False 5.0         0.241812
                  500.0    0.00005 False         False 5.0         0.292622
         resnet56 100.0    0.00005 False         False 5.0         0.218156
                  200.0    0.00005 False         False 5.0         0.227405
                  300.0    0.00005 False         False 5.0         0.261581
                  500.0    0.00005 False         False 5.0         0.340771
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN         0.265901
         resnet32 NaN      NaN     NaN           NaN   NaN         0.251843
         resnet44 NaN      NaN     NaN           NaN   NaN         0.230597
         resnet56 NaN      NaN     NaN           NaN   NaN         0.203734

                                                                   test_ece  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0         0.035559
                  200.0    0.00005 False         False 5.0         0.032431
                  300.0    0.00005 False         False 5.0         0.029491
                  500.0    0.00005 False         False 5.0         0.022058
         resnet32 100.0    0.00005 False         False 5.0         0.033863
                  200.0    0.00005 False         False 5.0         0.026254
                  300.0    0.00005 False         False 5.0         0.017446
                  500.0    0.00005 False         False 5.0         0.021553
         resnet44 100.0    0.00005 False         False 5.0         0.027378
                  200.0    0.00005 False         False 5.0         0.016787
                  300.0    0.00005 False         False 5.0         0.022408
                  500.0    0.00005 False         False 5.0         0.076459
         resnet56 100.0    0.00005 False         False 5.0         0.021387
                  200.0    0.00005 False         False 5.0         0.023744
                  300.0    0.00005 False         False 5.0         0.055121
                  500.0    0.00005 False         False 5.0         0.125868
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN         0.023835
         resnet32 NaN      NaN     NaN           NaN   NaN         0.029178
         resnet44 NaN      NaN     NaN           NaN   NaN         0.026338
         resnet56 NaN      NaN     NaN           NaN   NaN         0.024071

                                                                   test_brier  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0           0.117510
                  200.0    0.00005 False         False 5.0           0.116414
                  300.0    0.00005 False         False 5.0           0.115537
                  500.0    0.00005 False         False 5.0           0.114025
         resnet32 100.0    0.00005 False         False 5.0           0.104528
                  200.0    0.00005 False         False 5.0           0.103256
                  300.0    0.00005 False         False 5.0           0.102886
                  500.0    0.00005 False         False 5.0           0.106565
         resnet44 100.0    0.00005 False         False 5.0           0.098130
                  200.0    0.00005 False         False 5.0           0.097914
                  300.0    0.00005 False         False 5.0           0.100881
                  500.0    0.00005 False         False 5.0           0.117055
         resnet56 100.0    0.00005 False         False 5.0           0.090550
                  200.0    0.00005 False         False 5.0           0.095007
                  300.0    0.00005 False         False 5.0           0.104352
                  500.0    0.00005 False         False 5.0           0.133081
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN           0.116038
         resnet32 NaN      NaN     NaN           NaN   NaN           0.102786
         resnet44 NaN      NaN     NaN           NaN   NaN           0.096835
         resnet56 NaN      NaN     NaN           NaN   NaN           0.088288

                                                                   test_auc  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0         0.895033
                  200.0    0.00005 False         False 5.0         0.894121
                  300.0    0.00005 False         False 5.0         0.888397
                  500.0    0.00005 False         False 5.0         0.885637
         resnet32 100.0    0.00005 False         False 5.0         0.934008
                  200.0    0.00005 False         False 5.0         0.924395
                  300.0    0.00005 False         False 5.0         0.931788
                  500.0    0.00005 False         False 5.0         0.897543
         resnet44 100.0    0.00005 False         False 5.0         0.898393
                  200.0    0.00005 False         False 5.0         0.873060
                  300.0    0.00005 False         False 5.0         0.842197
                  500.0    0.00005 False         False 5.0         0.820972
         resnet56 100.0    0.00005 False         False 5.0         0.947338
                  200.0    0.00005 False         False 5.0         0.914674
                  300.0    0.00005 False         False 5.0         0.906987
                  500.0    0.00005 False         False 5.0         0.892392
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN         0.884001
         resnet32 NaN      NaN     NaN           NaN   NaN         0.917649
         resnet44 NaN      NaN     NaN           NaN   NaN         0.876217
         resnet56 NaN      NaN     NaN           NaN   NaN         0.929494

                                                                     seed  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0         1234.0
                  200.0    0.00005 False         False 5.0         1234.0
                  300.0    0.00005 False         False 5.0         1234.0
                  500.0    0.00005 False         False 5.0         1234.0
         resnet32 100.0    0.00005 False         False 5.0         1234.0
                  200.0    0.00005 False         False 5.0         1234.0
                  300.0    0.00005 False         False 5.0         1234.0
                  500.0    0.00005 False         False 5.0         1234.0
         resnet44 100.0    0.00005 False         False 5.0         1234.0
                  200.0    0.00005 False         False 5.0         1234.0
                  300.0    0.00005 False         False 5.0         1234.0
                  500.0    0.00005 False         False 5.0         1234.0
         resnet56 100.0    0.00005 False         False 5.0         1234.0
                  200.0    0.00005 False         False 5.0         1234.0
                  300.0    0.00005 False         False 5.0         1234.0
                  500.0    0.00005 False         False 5.0         1234.0
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN         1234.0
         resnet32 NaN      NaN     NaN           NaN   NaN         1234.0
         resnet44 NaN      NaN     NaN           NaN   NaN         1234.0
         resnet56 NaN      NaN     NaN           NaN   NaN         1234.0

                                                                   prior_opt_lr  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0                  0.1
                  200.0    0.00005 False         False 5.0                  0.1
                  300.0    0.00005 False         False 5.0                  0.1
                  500.0    0.00005 False         False 5.0                  0.1
         resnet32 100.0    0.00005 False         False 5.0                  0.1
                  200.0    0.00005 False         False 5.0                  0.1
                  300.0    0.00005 False         False 5.0                  0.1
                  500.0    0.00005 False         False 5.0                  0.1
         resnet44 100.0    0.00005 False         False 5.0                  0.1
                  200.0    0.00005 False         False 5.0                  0.1
                  300.0    0.00005 False         False 5.0                  0.1
                  500.0    0.00005 False         False 5.0                  0.1
         resnet56 100.0    0.00005 False         False 5.0                  0.1
                  200.0    0.00005 False         False 5.0                  0.1
                  300.0    0.00005 False         False 5.0                  0.1
                  500.0    0.00005 False         False 5.0                  0.1
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN                  0.1
         resnet32 NaN      NaN     NaN           NaN   NaN                  0.1
         resnet44 NaN      NaN     NaN           NaN   NaN                  0.1
         resnet56 NaN      NaN     NaN           NaN   NaN                  0.1

                                                                   prior_opt_iters  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0                  1000.0
                  200.0    0.00005 False         False 5.0                  1000.0
                  300.0    0.00005 False         False 5.0                  1000.0
                  500.0    0.00005 False         False 5.0                  1000.0
         resnet32 100.0    0.00005 False         False 5.0                  1000.0
                  200.0    0.00005 False         False 5.0                  1000.0
                  300.0    0.00005 False         False 5.0                  1000.0
                  500.0    0.00005 False         False 5.0                  1000.0
         resnet44 100.0    0.00005 False         False 5.0                  1000.0
                  200.0    0.00005 False         False 5.0                  1000.0
                  300.0    0.00005 False         False 5.0                  1000.0
                  500.0    0.00005 False         False 5.0                  1000.0
         resnet56 100.0    0.00005 False         False 5.0                  1000.0
                  200.0    0.00005 False         False 5.0                  1000.0
                  300.0    0.00005 False         False 5.0                  1000.0
                  500.0    0.00005 False         False 5.0                  1000.0
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN                  1000.0
         resnet32 NaN      NaN     NaN           NaN   NaN                  1000.0
         resnet44 NaN      NaN     NaN           NaN   NaN                  1000.0
         resnet56 NaN      NaN     NaN           NaN   NaN                  1000.0

                                                                   train_time_s  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0              1456.20
                  200.0    0.00005 False         False 5.0              1447.22
                  300.0    0.00005 False         False 5.0              1438.60
                  500.0    0.00005 False         False 5.0              1459.51
         resnet32 100.0    0.00005 False         False 5.0              2043.82
                  200.0    0.00005 False         False 5.0              2043.48
                  300.0    0.00005 False         False 5.0              2053.79
                  500.0    0.00005 False         False 5.0              2040.42
         resnet44 100.0    0.00005 False         False 5.0              2595.57
                  200.0    0.00005 False         False 5.0              2510.80
                  300.0    0.00005 False         False 5.0              2471.93
                  500.0    0.00005 False         False 5.0              2466.44
         resnet56 100.0    0.00005 False         False 5.0              3053.46
                  200.0    0.00005 False         False 5.0              3099.27
                  300.0    0.00005 False         False 5.0              3069.49
                  500.0    0.00005 False         False 5.0              3054.99
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN                  NaN
         resnet32 NaN      NaN     NaN           NaN   NaN                  NaN
         resnet44 NaN      NaN     NaN           NaN   NaN                  NaN
         resnet56 NaN      NaN     NaN           NaN   NaN                  NaN

                                                                   eval_time_s  \
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0                7.91
                  200.0    0.00005 False         False 5.0                7.47
                  300.0    0.00005 False         False 5.0                8.87
                  500.0    0.00005 False         False 5.0                8.06
         resnet32 100.0    0.00005 False         False 5.0                9.99
                  200.0    0.00005 False         False 5.0                9.90
                  300.0    0.00005 False         False 5.0                9.51
                  500.0    0.00005 False         False 5.0                9.60
         resnet44 100.0    0.00005 False         False 5.0               11.05
                  200.0    0.00005 False         False 5.0               11.62
                  300.0    0.00005 False         False 5.0               11.36
                  500.0    0.00005 False         False 5.0               10.90
         resnet56 100.0    0.00005 False         False 5.0               13.24
                  200.0    0.00005 False         False 5.0               12.81
                  300.0    0.00005 False         False 5.0               12.53
                  500.0    0.00005 False         False 5.0               12.62
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN                 NaN
         resnet32 NaN      NaN     NaN           NaN   NaN                 NaN
         resnet44 NaN      NaN     NaN           NaN   NaN                 NaN
         resnet56 NaN      NaN     NaN           NaN   NaN                 NaN

                                                                   laplace_iters
model    backbone features lr      use_embedding sqrt  batch_size
ALaplace resnet20 100.0    0.00005 False         False 5.0              100000.0
                  200.0    0.00005 False         False 5.0              100000.0
                  300.0    0.00005 False         False 5.0              100000.0
                  500.0    0.00005 False         False 5.0              100000.0
         resnet32 100.0    0.00005 False         False 5.0              100000.0
                  200.0    0.00005 False         False 5.0              100000.0
                  300.0    0.00005 False         False 5.0              100000.0
                  500.0    0.00005 False         False 5.0              100000.0
         resnet44 100.0    0.00005 False         False 5.0              100000.0
                  200.0    0.00005 False         False 5.0              100000.0
                  300.0    0.00005 False         False 5.0              100000.0
                  500.0    0.00005 False         False 5.0              100000.0
         resnet56 100.0    0.00005 False         False 5.0              100000.0
                  200.0    0.00005 False         False 5.0              100000.0
                  300.0    0.00005 False         False 5.0              100000.0
                  500.0    0.00005 False         False 5.0              100000.0
Laplace  resnet20 NaN      NaN     NaN           NaN   NaN                   NaN
         resnet32 NaN      NaN     NaN           NaN   NaN                   NaN
         resnet44 NaN      NaN     NaN           NaN   NaN                   NaN
         resnet56 NaN      NaN     NaN           NaN   NaN                   NaN

In [5]:
best_nll_per_backbone = df.loc[df.groupby(["backbone", "features"])["test_nll"].idxmin()]
best_nll_per_backbone[["model", "test_nll", "test_ece", "test_auc", "backbone", "lr", "sqrt", "features", "use_embedding", "batch_size"]]

,model,test_nll,test_ece,test_auc,backbone,lr,sqrt,features,use_embedding,batch_size
9,ALaplace,0.274175,0.035559,0.895033,resnet20,0.00005,False,100.0,False,5.0
14,ALaplace,0.267225,0.032431,0.894121,resnet20,0.00005,False,200.0,False,5.0
10,ALaplace,0.261697,0.029491,0.888397,resnet20,0.00005,False,300.0,False,5.0
12,ALaplace,0.251531,0.022058,0.885637,resnet20,0.00005,False,500.0,False,5.0
11,ALaplace,0.267116,0.033863,0.934008,resnet32,0.00005,False,100.0,False,5.0
13,ALaplace,0.252609,0.026254,0.924395,resnet32,0.00005,False,200.0,False,5.0
18,ALaplace,0.244238,0.017446,0.931788,resnet32,0.00005,False,300.0,False,5.0
19,ALaplace,0.250693,0.021553,0.897543,resnet32,0.00005,False,500.0,False,5.0
1,ALaplace,0.243292,0.027378,0.898393,resnet44,0.00005,False,100.0,False,5.0
2,ALaplace,0.234151,0.016787,0.873060,resnet44,0.00005,False,200.0,False,5.0
8,ALaplace,0.241812,0.022408,0.842197,resnet44,0.00005,False,300.0,False,5.0
5,ALaplace,0.292622,0.076459,0.820972,resnet44,0.00005,False,500.0,False,5.0
16,ALaplace,0.218156,0.021387,0.947338,resnet56,0.00005,False,100.0,False,5.0
7,ALaplace,0.227405,0.023744,0.914674,resnet56,0.00005,False,200.0,False,5.0
3,ALaplace,0.261581,0.055121,0.906987,resnet56,0.00005,False,300.0,False,5.0
6,ALaplace,0.340771,0.125868,0.892392,resnet56,0.00005,False,500.0,False,5.0